### ISSUE TITLE
How can i denormalize after normalize ?

### ISSUE THREAD

**Issue by jiaohuix** [ARBML/tnkeeh#10]
Hello, thank you for your excellent work! Excuse me, how can I remove normalization after normalizaton? I am doing machine translation in Chinese and Arabic, which needs to normalize during training and denormalize when inference to  get a reasonable score. Thanks!

**Comment by zaidalyafeai** [comment]
Normalization can't be undone because it is not one-to-one.

**Comment by jiaohuix** [comment]
> Normalization can't be undone because it is not one-to-one.

ok, I know, thank you！！！
