### ISSUE TITLE
Tanween is not removed from diacritics

### ISSUE THREAD

**Issue by piraka9011** [ARBML/tnkeeh#8]
Salam! Great package!

I noticed the following diacritic wasn't removed from my text ('ً'). Note that it's hard to see in the GH editor.

```sh
'ً'
```

I couldn't understand how the regex for the diacritics worked in this package so I couldn't open a PR.
But wanted to point this out in case someone knows how to add this as a case.

**Comment by zaidalyafeai** [comment]
Thanks @piraka9011 , fixed in source, will update pypi soon.
